### ISSUE TITLE
Rename VersionReq to Range

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/semver#138]
See the discussion in https://github.com/steveklabnik/semver-parser/issues/21

If we want to make the names consistent in `semver_parser` and the npm `semver` package then I think it would make sense to make them consistent here too.

Let's discuss this over in https://github.com/steveklabnik/semver-parser/issues/21 first and then come back here and apply. We might not want to worry about renaming things at all.

# Mentoring instructions

Leave a comment here on the thread and we'll work out how to get started.

**Comment by dtolnay** [comment]
I would prefer not to make this change.

VersionReq is a different thing from what the spec calls Range (https://github.com/semver/semver/blob/efcff2c838c9945f79bfd21c1df0073271bcc29c/ranges.md#semantic-version-range-specification-semver-ranges). Namely a Range is *"a set of 1 or more Comparator Sets, joined by `||`"*. That's not a thing that exists in this crate because Cargo does not do `||`.

The "requirement" terminology is consistent with the way Cargo presents this concept to its users, such as in https://doc.rust-lang.org/1.52.1/cargo/reference/specifying-dependencies.html#tilde-requirements. Teaching them about "tilde requirements" is more intuitive IMO than teaching them "tilde comparator sets" or "tilde ranges", and so it's better for this crate to be consistent with that presentation than to be consistent with npm.
