### ISSUE TITLE
Support for rusqlite?

### ISSUE THREAD

**Issue by thomcc** [dtolnay/semver#204]
Right now you have diesel support. Would you accept a patch adding (optional) rusqlite support?

**Comment by dtolnay** [comment]
I think I would prefer not to build this into the semver crate. Part of the reason is that rusqlite has released a large number of breaking changes over the past year or two, which is incompatible with us releasing 1.0.0 of this crate that should last for a long time. But also even with a stable version of rusqlite, I'm not convinced that enough of the user base of the semver crate would benefit from this to justify it.

**Comment by thomcc** [comment]
Totally forgot I filed this (and surprised I did, honestly). I'm now one of the maintainers of rusqlite, and think that for something like this, having rusqlite have a semver feature would make more sense than semver having a rusqlite feature.

(... Not that I particularly plan on adding that, as I agree, it seems a bit niche)
