### ISSUE TITLE
Make Version::parse const

### ISSUE THREAD

**Issue by rakshith-ravi** [dtolnay/semver#231]
It would be nice to have the version::parse function as a const function, so that we can parse things like the crate's version into a const variable (I currently get it from `clap_version!()`, but I'd like that to be useable as a `Version` variable). I believe this requires rust to stabilize panicing and unwraping in const fns, but I was just wondering if this is possible sometime in the future.

**Comment by dtolnay** [comment]
I am not opposed to this, but I am going to close because I don't feel it's necessarily useful to track in an issue that's not currently actionable. I would be prepared to consider a PR whenever this turns out to be possible to implement.

**Comment by GilShoshan94** [comment]
Hi @dtolnay, now in 2024 is yet possible or are we still missing something a feature in Rust for that ? 

I looked around and I found the [konst crate](https://docs.rs/konst/latest/konst/) that has capabilities to do some parsing in const context. When I took a look inside the source code in order to evaluate if I can take the relevant part and make a PR here, I hit a complexity wall and do not understand what's going on to be honest ...

Any idea if this is actionable now?
