### ISSUE TITLE
VersionReq for prereleases matches release versions

### ISSUE THREAD

**Issue by tarcieri** [dtolnay/semver#236]
This is a somewhat analogous problem to #172, which got me looking at the SemVer ranges spec.

https://github.com/semver/semver/blob/efcff2c838c9945f79bfd21c1df0073271bcc29c/ranges.md#semantic-version-range-specification-semver-ranges

> SemVer Versions that include PRERELEASE identifiers are assumed to be unstable and/or incomplete.
>
> Additionally, the presence of PRERELEASE identifiers in a version such as I.J.K-PRERELEASE causes the SemVer Version > to have a lower precedence than I.J.K. Thus, it could cause a Range such as <2.0.0 to include the version 2.0.0-rc.0,
> which likely contains breaking API changes that the consumer is not prepared to handle.
>
> To avoid surprising behavior for consumers...

I feel like this sort of "surprising" behavior exists in the interpretation of these `VersionReq`s:

- `2.0.0-rc.0`
- `^2.0.0-rc.0`

These are interpreted as: `>=2.0.0-rc.0, <3.0.0`

To me falls under the "surprising behavior for consumers" category. It means anyone who uses such a requirement will be automatically opted in to upgrading to a final 2.0.0 release, which is problematic if any breaking changes occur between `2.0.0-rc.0` and the final `2.0.0` release.

It's possible to avoid this by (as the end user) writing this requirement explicitly as `=2.0.0-rc.0`, which is what I always end up doing to avoid the aforementioned breakages. But per my reading of prerelease handling in the ranges spec, prereleases are supposed to be disjoint from release versions specifically to address that problem.

It seems like these prerelease `VersionReq`s should expand to something much more restrictive, such as `>=2.0.0-rc.0, <2.0.0`.

**Comment by dtolnay** [comment]
I've discussed this exact behavior with @steveklabnik who is a co-maintainer of the spec, as part of the crate handover, and we have the impression that this treatment of pre-releases is intentional.

Now if Cargo were to decide to change its interpretation of pre-release reqs in a future version (via a Cargo RFC), this crate would follow suite, since the scope is explicitly to implement Cargo's interpretation of SemVer. But neither of us had the impression that was likely to happen.
