### ISSUE TITLE
Support VerReq with date

### ISSUE THREAD

**Issue by cathaysia** [dtolnay/semver#302]
There is a version with date:

https://github.com/microsoft/vscode-python/blob/203f58bc169afc5a731557633d25722bed038bd1/package.json#L47

and `VersionReq("^1.82.0-20230830").is_matched("1.82")` will be true.

Have you considered fixing this problem?

**Comment by ehuss** [comment]
Sorry, I'm not quite understanding the question. This package follows [SemVer](https://semver.org/), which supports pre-release identifiers after the `-`. So:

```rust
use semver::*;
fn main() {
    println!("{}", VersionReq::parse("^1.82.0-20230830").unwrap().matches(&Version::parse("1.82.0-20230830").unwrap()));
    println!("{}", VersionReq::parse("^1.82.0-20240101").unwrap().matches(&Version::parse("1.82.0-20210101").unwrap()));
}
```

returns true and then false.

The SemVer doc above describes how pre-release identifiers are compared. If you're asking for different semantics than the SemVer docs, that is unlikely to be accepted since this package only implements SemVer as it is documented.

**Comment by cathaysia** [comment]
Sorry, this may be my own problem. I'm closing it now
