### ISSUE TITLE
Partial Order on version requirements

### ISSUE THREAD

**Issue by Ericson2314** [dtolnay/semver#83]
The rule would be

```
x ≤ y = { v : x.matches(v) } ⊂ { v : y.matches(v) }
```

or in English, a version requirement is considered less than another if everything it matches the other also matches.

(Also, note to self if I implement it, this is textbook thing to use https://github.com/BurntSushi/quickcheck to test)

**Comment by steveklabnik** [comment]
Sorry, what specifically is the issue here?

**Comment by Ericson2314** [comment]
Adding a PartialOrd impl.

**Comment by Ericson2314** [comment]
Sorry, I had meant to write more than that. The partial order would be whats commonly called "ordered by inclusion" where the greater objects contain lesser objects. Predicates are basically equivalent to the sets they accept, so in this case 1 version req would be greater than another if everything the other matches it also matches. Bigger <-> laxer requirements, basically.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate.

The most recent release has a VersionReq type that exposes the comparators and operators publicly (unlike when this issue was opened), so I would prefer if this logic were now implemented downstream instead. If it turns out being needed by lots of projects, we can reevaluate including it here.
